# Generated by Django 5.0.2 on 2024-03-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='flag',
            field=models.ImageField(blank=True, null=True, upload_to='race_layout/'),
        ),
    ]
